from sankhya_client import SankhyaClient
import json

client = SankhyaClient()

def query(sql, label=""):
    print("=" * 80)
    print(f"--- {label} ---")
    res = client.execute_query(sql)
    f_meta = [f.get("name") for f in res.get("responseBody", {}).get("fieldsMetadata", [])]
    rows = res.get("responseBody", {}).get("rows", [])
    print(f"Total registros: {len(rows)}")
    for r in rows:
        print(dict(zip(f_meta, r)))
    return rows

# 1. Verificar notas faturadas e pedidos vinculados aos contratos 8 e 332 na TGFCAB
query("""
SELECT 
    TGFCAB.NUMCONTRATO,
    TGFCAB.TIPMOV,
    TGFCAB.CODTIPOPER,
    COUNT(DISTINCT TGFCAB.NUNOTA) AS QTD_NOTAS,
    SUM(TGFITE.QTDNEG) AS TOTAL_QTD,
    SUM(TGFITE.VLRTOT) AS TOTAL_VALOR
FROM TGFCAB
INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA
WHERE TGFCAB.NUMCONTRATO IN (8, 332)
GROUP BY TGFCAB.NUMCONTRATO, TGFCAB.TIPMOV, TGFCAB.CODTIPOPER
""", "Movimentações diretas de TGFCAB por Contrato (8 vs 332)")

# 2. Verificar o que a query do Dash 2302 retorna exatamente para os contratos 8 e 332
query("""
SELECT 
    LGH_LICITECON.NUMCONTRATO,
    TCSCON.AD_PREGAO,
    LGH_LICITECON.CODPROD,
    TGFPRO.DESCRPROD,
    LGH_LICITECON.QTDEPREVISTA,
    -- Subquery de faturado atual do Dash 2302 (por Pregão)
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 INNER JOIN TCSCON CON ON CON.NUMCONTRATO = TGFCAB.NUMCONTRATO
	 WHERE TGFCAB.TIPMOV = 'V' AND 
		 TGFCAB.SERIENOTA = 2 AND 
		 TGFCAB.CODTIPOPER IN ('1000','1100','1107') AND 
		 CON.AD_PREGAO = TCSCON.AD_PREGAO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD) AS QTD_FAT_POR_PREGAO,
    -- Faturado específico DESTE contrato (por NUMCONTRATO)
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 WHERE TGFCAB.TIPMOV = 'V' AND 
		 TGFCAB.SERIENOTA = 2 AND 
		 TGFCAB.CODTIPOPER IN ('1000','1100','1107') AND 
		 TGFCAB.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD) AS QTD_FAT_POR_CONTRATO,
    -- Subquery de programado atual do Dash 2302 (por Pregão)
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 INNER JOIN TCSCON CON ON CON.NUMCONTRATO = TGFCAB.NUMCONTRATO
	 WHERE TGFCAB.TIPMOV = 'P' AND 
		 TGFCAB.SERIENOTA IS NULL AND 
		 TGFCAB.CODTIPOPER IN ('910','911','1183') AND 
		 CON.AD_PREGAO = TCSCON.AD_PREGAO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD AND 
		 TGFITE.PENDENTE = 'S' AND 
		 TGFITE.QTDNEG > TGFITE.QTDENTREGUE) AS QTD_PROG_POR_PREGAO,
    -- Programado específico DESTE contrato (por NUMCONTRATO)
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 WHERE TGFCAB.TIPMOV = 'P' AND 
		 TGFCAB.SERIENOTA IS NULL AND 
		 TGFCAB.CODTIPOPER IN ('910','911','1183') AND 
		 TGFCAB.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD AND 
		 TGFITE.PENDENTE = 'S' AND 
		 TGFITE.QTDNEG > TGFITE.QTDENTREGUE) AS QTD_PROG_POR_CONTRATO
FROM LGH_LICITECON
INNER JOIN TCSCON ON TCSCON.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO
INNER JOIN TGFPRO ON TGFPRO.CODPROD = LGH_LICITECON.CODPROD
WHERE LGH_LICITECON.NUMCONTRATO IN (8, 332)
""", "Comparativo: Cálculo por Pregão vs Cálculo por Contrato")
