from sankhya_client import SankhyaClient

client = SankhyaClient()

sql = """
SELECT 
    LGH_LICITECON.NUMCONTRATO,
    TCSCON.AD_PREGAO,
    LGH_LICITECON.CODPROD,
    LGH_LICITECON.QTDEPREVISTA,
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 INNER JOIN TCSCON CON ON CON.NUMCONTRATO = TGFCAB.NUMCONTRATO
	 WHERE TGFCAB.TIPMOV = 'P' AND 
		 TGFCAB.SERIENOTA IS NULL AND 
		 TGFCAB.CODTIPOPER IN ('910','911','1183') AND 
		 CON.AD_PREGAO = TCSCON.AD_PREGAO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD AND 
		 TGFITE.PENDENTE = 'S' AND 
		 TGFITE.QTDNEG > TGFITE.QTDENTREGUE) AS PROG_ATUAL,
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 INNER JOIN TCSCON CON ON CON.NUMCONTRATO = TGFCAB.NUMCONTRATO
	 WHERE TGFCAB.TIPMOV = 'V' AND 
		 TGFCAB.SERIENOTA = 2 AND 
		 TGFCAB.CODTIPOPER IN ('1000','1100','1107') AND 
		 CON.AD_PREGAO = TCSCON.AD_PREGAO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD) AS FAT_ATUAL,
    (SUM(LGH_LICITECON.QTDEPREVISTA) - 
		(SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
		 FROM TGFCAB 
		 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
		 INNER JOIN TCSCON CON ON CON.NUMCONTRATO = TGFCAB.NUMCONTRATO
		 WHERE TGFCAB.TIPMOV = 'V' AND
			TGFCAB.SERIENOTA = 2 AND
			TGFCAB.CODTIPOPER IN ('1000','1100','1107') AND
			CON.AD_PREGAO = TCSCON.AD_PREGAO AND
			TGFITE.CODPROD = LGH_LICITECON.CODPROD)) AS SLD_ATUAL
FROM LGH_LICITECON
INNER JOIN TCSCON ON TCSCON.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO
WHERE LGH_LICITECON.NUMCONTRATO IN (181, 286)
GROUP BY 
    LGH_LICITECON.NUMCONTRATO, TCSCON.AD_PREGAO, LGH_LICITECON.CODPROD, LGH_LICITECON.QTDEPREVISTA
"""
res = client.execute_query(sql)
rows = res.get("responseBody", {}).get("rows", [])
for r in rows:
    print(r)
