from sankhya_client import SankhyaClient

client = SankhyaClient()

sql_corrigido = """
SELECT 
    LGH_LICITECON.NUMCONTRATO,
    TCSCON.AD_PREGAO,
    LGH_LICITECON.CODPROD,
    TGFPRO.DESCRPROD,
    LGH_LICITECON.QTDEPREVISTA,
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 WHERE TGFCAB.TIPMOV = 'P' AND 
		 TGFCAB.SERIENOTA IS NULL AND 
		 TGFCAB.CODTIPOPER IN ('910','911','1183') AND 
		 TGFCAB.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD AND 
		 TGFITE.PENDENTE = 'S' AND 
		 TGFITE.QTDNEG > TGFITE.QTDENTREGUE) AS PROG_CORRIGIDO,
    (SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
	 FROM TGFCAB 
	 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
	 WHERE TGFCAB.TIPMOV = 'V' AND 
		 TGFCAB.SERIENOTA = 2 AND 
		 TGFCAB.CODTIPOPER IN ('1000','1100','1107') AND 
		 TGFCAB.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO AND 
		 TGFITE.CODPROD = LGH_LICITECON.CODPROD) AS FAT_CORRIGIDO,
    (SUM(LGH_LICITECON.QTDEPREVISTA) - 
		(SELECT ISNULL(SUM(TGFITE.QTDNEG),0) 
		 FROM TGFCAB 
		 INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA 
		 WHERE TGFCAB.TIPMOV = 'V' AND
			TGFCAB.SERIENOTA = 2 AND
			TGFCAB.CODTIPOPER IN ('1000','1100','1107') AND
			TGFCAB.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO AND
			TGFITE.CODPROD = LGH_LICITECON.CODPROD)) AS SLD_PRODUTO_CORRIGIDO
FROM LGH_LICITECON
INNER JOIN TCSCON ON TCSCON.NUMCONTRATO = LGH_LICITECON.NUMCONTRATO
INNER JOIN TGFPRO ON TGFPRO.CODPROD = LGH_LICITECON.CODPROD
WHERE LGH_LICITECON.NUMCONTRATO IN (8, 332)
GROUP BY 
    LGH_LICITECON.NUMCONTRATO, TCSCON.AD_PREGAO, LGH_LICITECON.CODPROD, TGFPRO.DESCRPROD, LGH_LICITECON.QTDEPREVISTA
ORDER BY LGH_LICITECON.CODPROD, LGH_LICITECON.NUMCONTRATO
"""

res = client.execute_query(sql_corrigido)
rows = res.get("responseBody", {}).get("rows", [])
print(f"{'CONTRATO':<10} | {'PREGÃO':<10} | {'CODPROD':<8} | {'PREV':<8} | {'PROG':<8} | {'FAT':<8} | {'SALDO':<8} | {'PRODUTO'}")
print("-" * 90)
for r in rows:
    c, p, cp, desc, prev, prog, fat, sld = r
    print(f"{c:<10} | {p:<10} | {cp:<8} | {prev:<8} | {prog:<8} | {fat:<8} | {sld:<8} | {desc[:30]}")
